dist: trusty
sudo: false

language: node_js
node_js:
  - 12
  - 10

addons:
  chrome: stable

cache:
  directories:
    - ./node_modules

install:
  - npm install codecov -g
  - npm install

script:
  - npm run lint
  - npm run test -- --no-watch --code-coverage --browsers ChromeHeadlessNoSandBox
  - npm run e2e

after_success:
  - codecov
